### ISSUE TITLE
Record routine check-ups

### ISSUE THREAD

**Issue by JacobWilson00358UWG** [ssrrtteeee/Healthcare-System#10]
Enter routine checkups.
Keep in mind systolic, diastolic blood pressure and pulse are integer values, weight (lb), height (in) are decimal values.

**Comment by ssrrtteeee** [comment]
Added functionality in commit [bc663f0](https://github.com/ssrrtteeee/Healthcare-System/commit/bc663f05874fa8b2cd51b3ae0f5b1dec197c461b). Still needs validation

**Comment by ssrrtteeee** [comment]
Fully integrated functionality in commit [d4a9970](https://github.com/ssrrtteeee/Healthcare-System/commit/d4a997075b2f340d90145862696868f65a7fd1d9).
