### ISSUE TITLE
Request tests

### ISSUE THREAD

**Issue by JacobWilson00358UWG** [ssrrtteeee/Healthcare-System#14]
Order tests for a visit.
Before the user confirms the tests ordered, the user can remove or add more tests to the order.
The details of the tests ordered should be present so that the user knows what's being ordered.

The typical tests include:
- white blood cell (WBC)
- Low Density Lipoproteins (LDL)
- hepatitis A test
- hepatitis B test
and so on.

**Comment by ssrrtteeee** [comment]
Done in commit [842c9c4](https://github.com/ssrrtteeee/Healthcare-System/commit/842c9c47cfdefb0f16a4f15497fb86ed5a76bb2b).
