### ISSUE TITLE
Admin functionality

### ISSUE THREAD

**Issue by JacobWilson00358UWG** [ssrrtteeee/Healthcare-System#16]
There should be an interface provided for administers.
Admin features:
- Query interface
  - The administrator can pose queries in SQL and view the result in tabular format.
- Report for dates
  - Select any two dates and view a report containing the information about all the visits during the time specified. The visit information should include the visit date, patient id, name, the names of the doctor and nurse involved, the tests ordered, test perform date, tests result abnormality, and diagnosis. The result should be sorted by the visit date followed by the last name of the patient.

**Comment by ssrrtteeee** [comment]
Not required until Final Project Demo: Dec. 2 (Mon.), Dec. 3 (Tue.).
