### ISSUE TITLE
Password hashing

### ISSUE THREAD

**Issue by JacobWilson00358UWG** [ssrrtteeee/Healthcare-System#17]
Store hashed passwords for users in the DB (you may use any hashing mechanism --make sure to cite and credit the sources in comments)

**Comment by ssrrtteeee** [comment]
Not required until Final Project Demo: Dec. 2 (Mon.), Dec. 3 (Tue.).

**Comment by ssrrtteeee** [comment]
Added in commit [0342f21](https://github.com/ssrrtteeee/Healthcare-System/commit/0342f21983fb43c231ab0fee97d76437018b8ec1).
