### ISSUE TITLE
Enter initial diagnosis

### ISSUE THREAD

**Issue by JacobWilson00358UWG** [ssrrtteeee/Healthcare-System#18]
Enter initial diagnosis.
Note that initial diagnosis is optional at the routine checkup stage. The nurse can fill in it later after the doctor exams the patient.

**Comment by ssrrtteeee** [comment]
Done in commit [842c9c4](https://github.com/ssrrtteeee/Healthcare-System/commit/842c9c47cfdefb0f16a4f15497fb86ed5a76bb2b).
