### ISSUE TITLE
Patient registration

### ISSUE THREAD

**Issue by JacobWilson00358UWG** [ssrrtteeee/Healthcare-System#3]
- Register a patient:
    - Use dropdown box for gender and state. Perform proper field validation on zip, phone number, etc.
    - The system doesn't store which user helped with registering the patient.

**Comment by ssrrtteeee** [comment]
Added all functionality, but field validation in commit [7588f3b](https://github.com/ssrrtteeee/Healthcare-System/commit/7588f3b67195d4847df95af84c2297285b03d944).
